version: "3.8"

services:
  db:
    container_name: mongodb
    restart: on-failure
    build:
      context: .
      dockerfile: Dockerfile.mongo
    ports:
      - "27017:27017"
    volumes:
      - mongodb_data:/data/db
    command: mongod --bind_ip_all
    healthcheck:
      test: ["CMD", "mongosh", "--host", "localhost", "--port", "27017",  "--eval", "db.serverStatus()"]
      interval: 10s
      timeout: 5s
      retries: 3
      start_period: 30s
    networks:
      - 295fsnetwork

  mongo-express:
    container_name: mongoadmin
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    image: mongo-express
    ports:
      - "8081:8081"
    #env_file:
    #  - ./.envmongoadmin
    environment:
      - ME_CONFIG_MONGODB_SERVER=mongodb
      - ME_CONFIG_MONGODB_PORT=27017
      - ME_CONFIG_MONGODB_URL= mongodb://mongodb:27017/
    networks:
      - 295fsnetwork

  backend:
    container_name: 295fsbe
    restart: on-failure
    depends_on:
      db:
        condition: service_healthy
    image: hftamayo/295fs_be:stable
    ports:
      - "5000:5000"
    networks:
      - 295fsnetwork

  frontend:
    container_name: 295fsfe
    restart: on-failure
    depends_on:
      - backend
    image: hftamayo/295fs_fe:stable
    ports:
      - "3000:3000"
    networks:
      - 295fsnetwork

volumes:
  mongodb_data:

networks:
  295fsnetwork:
